### ISSUE TITLE
store.accrescent.app 403 Forbidden

### ISSUE THREAD

**Issue by JanWaldhorn** [accrescent/accrescent.app#10]
i tried to get to the link https://store.accrescent.app/ via https://accrescent.app/features but i only get a 403

**Comment by lberrymage** [comment]
Thanks. This is because https://store.accrescent.app originally had a browsable file index, so it was linked for informational purposes. I decided to disable the indexing to prevent people from installing apps incorrectly, but mistakenly didn't remove the hyperlink. I'll go ahead and fix that.
