### ISSUE TITLE
Accrescent DNS wrong records about mail security

### ISSUE THREAD

**Issue by Mello7sh3i** [accrescent/accrescent.app#17]
Hey,

not a problem about the website hitself, but don't know where report it. Just to let you know that your domain currently has two email configuration errors :

Your SPF policy is incorrect because it's published as an SPF record, when it should be published as a TXT record.
And your dmarc policy is also invalid for reports. The "mailto:" tag before the e-mail address is missing, it should be like this : 
"v=DMARC1; p=reject; adkim=s; aspf=s; rua=mailto:dmarc@accrescent.app; ruf=mailto:dmarc@accrescent.app"

You can check your domain errors here : https://www.hardenize.com/

**Comment by lberrymage** [comment]
Thank you. These issues have now been resolved.
