### ISSUE TITLE
Access to submit apps

### ISSUE THREAD

**Issue by HaleTom** [accrescent/accrescent.app#21]
From https://accrescent.app/faq I tried adding an app via: https://dev.accrescent.app/login

Logging in with GitHub I got:

	Registration not permitted
	Accrescent developer registration is currently invite-only. Please come back when registration opens for everyone.

https://accrescent.app/docs/guide/getting-started/new-app.html says:

	To upload a new app, click the "New app" button on your dashboard.
	
How does one get access to this?  Perhaps a link to the contact info would help in the 2nd and 3rd links above?

**Comment by lberrymage** [comment]
Thanks for reporting this! The sign-up process is now documented.

**Comment by HaleTom** [comment]
Excellent, cheers!!
