### ISSUE TITLE
Accrescent ad SDK

### ISSUE THREAD

**Issue by jujubeja** [accrescent/accrescent.app#23]
- Publishing apps at Accrescent allows ads, but only when using the **Accrescent ad SDK**.
 
**Accrescent ad SDK** features
- Advertisement Image Video Source can only be accrescent link | raw.githubusercontent.com | gitlab, etc.
- Skip ads without waiting for a timer.
- Ads are clickable links Amazon eBay playstore google.com/search?q=`Accrescent` and other popular sites.
The accrescent ad SDK does not allow personal websites to link, because the app only needs to confirm the ip time of the visit with the personal website to track and analyze the user.

**Comment by lberrymage** [comment]
This is not planned.
